=== rokasstankevicius/Praktinis_Darbas_2/ServerRentingService/src/main/resources/userdataToWDSL.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.ServerRenting.lt/viko/eif/rstankevicius/serverrenting/api/userDataCheck"
           xmlns:tns="http://www.ServerRenting.lt/viko/eif/rstankevicius/serverrenting/api/userDataCheck">

    <xs:element name="getUserDataCheckRequest">
      <xs:complexType>
        <xs:sequence>
          <xs:element name="id" type="xs:int"/>
        </xs:sequence>
      </xs:complexType>
    </xs:element>

    <xs:element name="getUserDataCheckResponse">
      <xs:complexType>
        <xs:sequence>
          <xs:element name="Check" type="tns:userDataCheck"/>
        </xs:sequence>
      </xs:complexType>
    </xs:element>


      <xs:complexType name="userDataCheck">
        <xs:sequence>
          <xs:element type="xs:boolean" name="hasDedicatedServers" default="false"/>
          <xs:element type="xs:boolean" name="hasCloudServers" default="false"/>
          <xs:element type="xs:float" name="price"/>
          <xs:element type="xs:int" name="amountOfDedicatedServers" default="0"/>
          <xs:element type="xs:int" name="amountOfCloudServers" default="0"/>
        </xs:sequence>
      </xs:complexType>


    <xs:complexType name="dedicatedServersType">
      <xs:sequence>
        <xs:element type="xs:int" name="id"/>
        <xs:element type="xs:int" name="storageSpace"/>
        <xs:element type="xs:string" name="cpu"/>
        <xs:element type="xs:string" name="ram"/>
        <xs:element type="xs:string" name="os"/>
      </xs:sequence>
    </xs:complexType>

    <xs:complexType name="cloudServersType">
      <xs:sequence>
        <xs:element type="xs:int" name="id"/>
        <xs:element type="xs:int" name="vCores"/>
        <xs:element type="xs:int" name="storageSpace"/>
        <xs:element type="xs:string" name="ram"/>
      </xs:sequence>
    </xs:complexType>


    <xs:complexType name="userPackageType">
      <xs:sequence>
        <xs:element type="xs:int" name="id"/>
        <xs:element type="xs:string" name="name"/>
        <xs:element type="xs:float" name="price"/>
        <xs:element type="tns:dedicatedServersType" name="dedicatedServers" maxOccurs="unbounded"/>
        <xs:element type="tns:cloudServersType" name="cloudServers" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>

    <xs:element name="userData" type="tns:userDataType"/>
    <xs:complexType name="userDataType">
      <xs:sequence>
        <xs:element type="xs:int" name="id"/>
        <xs:element type="xs:string" name="username"/>
        <xs:element type="xs:string" name="password"/>
        <xs:element type="tns:userPackageType" name="userPackage"/>
      </xs:sequence>
    </xs:complexType>



</xs:schema>

=== rokasstankevicius/Praktinis_Darbas_2/ServerRentingService/userdata.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<userData xmlns="http://www.ServerRenting.lt/viko/eif/rstankevicius/serverrenting/api/userDataCheck"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.ServerRenting.lt/viko/eif/rstankevicius/serverrenting/api/userDataCheck userdataToWDSL.xsd">

    <id>1</id>
    <username>Jeff</username>
    <password>ToBBy25</password>
    <userPackage>
        <id>1</id>
        <name>Gold</name>
        <price>169.99</price>
        <dedicatedServers>
            <id>1</id>
            <storageSpace>1</storageSpace>
            <cpu>AMD Ryzen™ 5 PRO 3600</cpu>
            <ram>32 GB DDR4 3400</ram>
            <os>Windows Server</os>
        </dedicatedServers>
        <dedicatedServers>
            <id>2</id>
            <storageSpace>2</storageSpace>
            <cpu>AMD Ryzen™ 9 PRO 3900</cpu>
            <ram>128 GB DDR4 3400</ram>
            <os>Ubuntu</os>
        </dedicatedServers>
        <cloudServers>
            <id>1</id>
            <vCores>2</vCores>
            <storageSpace>80</storageSpace>
            <ram>4 GB DDR4 3400</ram>
        </cloudServers>
    </userPackage>
</userData>
